name: Build Image and deploy a container to an Azure Web App
on:    
  workflow_dispatch:
    branches:
         - main
    inputs:
      environment:
        description: 'azure environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prod 

env:
  AZURE_RESOURCE_GROUP: Test-Azure-POC  # target resource, must match the {resource-group-name} you setup in the pre-requisties
  WEB_APP_NAME: test-azure-poc-03         # set the name for the Web App on Azure
  CONTAINER_IMAGE_NAME: test-azure-poc # set the name for the container image 
  ACR_NAME: testazurepoc               # set the name for the Azure Container Registry
  ACR_LOGIN_SERVER: testazurepoc.azurecr.io # fqdn for the Azure Container Registry
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }} # user name for accessing Azure Container Registry
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }} # password for accesing the Azure Container Registry

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'dev'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login for az cli commands 
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
         registry: ${{ env.ACR_LOGIN_SERVER }}
         username: ${{ env.ACR_USERNAME }}
         password: ${{ env.ACR_PASSWORD }}
         logout: false

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
         context: ./application/
         push: true
         tags: ${{ env.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
         file: ./application/Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
